from .elements import Citation as Citation, Doc as Doc, EMPTY_ELEMENTS as EMPTY_ELEMENTS, Element as Element, ListContainer as ListContainer, Math as Math, OrderedList as OrderedList, Quoted as Quoted, Table as Table, from_json as from_json
from _typeshed import Incomplete

def load(input_stream: Incomplete | None = None): ...
def dump(doc, output_stream: Incomplete | None = None): ...
def toJSONFilters(*args, **kwargs): ...
def toJSONFilter(*args, **kwargs): ...
def run_filters(actions, prepare: Incomplete | None = None, finalize: Incomplete | None = None, input_stream: Incomplete | None = None, output_stream: Incomplete | None = None, doc: Incomplete | None = None, stop_if: Incomplete | None = None, **kwargs): ...
def run_filter(action, *args, **kwargs): ...
