import types
from _typeshed import Incomplete

def decode_ica(lst): ...
def debug(*args, **kwargs) -> None: ...
def get_caller_name(): ...
def check_type(value, oktypes): ...
def check_group(value, group): ...
def check_type_or_value(value, oktypes, okvalue): ...
def encode_dict(tag, content): ...
def load_pandoc_version(): ...
def load_pandoc_reader_options(): ...

class ContextImport:
    module: Incomplete
    extra_dir: Incomplete
    def __init__(self, module, extra_dir: Incomplete | None = None) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
